#!/bin/sh

# whatever you want to autostart
exec picom --experimental-backends &
exec sxhkd &
exec playerctld daemon &
exec feh --bg-fill /home/evan/.wallpaper/Wallpaper-Bridge.jpg &
exec /usr/lib/geoclue-2.0/demos/agent &

# notifications
# starts tiramisu script that writes to a file...yes, yes, I know
~/.config/dwm/scripts/./cake.sh &

# bar & dwm, required...
~/.config/dwm/scripts/./bar.sh &
dwm
