#!/bin/sh

# whatever you want to autostart
exec picom --experimental-backends &
exec sxhkd &
exec playerctld daemon &
exec feh --bg-fill /home/evan/.wallpaper/Wallpaper-Moon.jpg &

# bar & dwm, required...
~/.config/dwm/scripts/./bar.sh &
dwm
