name: install

on:
  push:
    branches:
      - main

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2.3.3
      - name: Bare setup
        run: bash bin/install
      - name: Install packages
        run: brew install coreutils
      - name: System defaults
        run: bash macos
  linux:
    runs-on: ubunut-latest
    steps:
      - name: Cancel previous runs
        users: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token  }}
      - uses: actions/checkout@v2.3.3
      - name: Bare setup
        run: bash bin/install
      - name: Install packages
        run: sudo zypper --non-interactive in fish
