name: install

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 12 * * 6'
jobs:
  macos:
    runs-on: macos-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2.3.3
      - name: Bare setup
        run: bash bin/install
      - name: Install packages
        run: brew install coreutils
      - name: System defaults
        run: bash macos
      - name: Show home dir
        run: cd $HOME && ls -a
  # linux:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Cancel previous runs
  #       uses: styfle/cancel-workflow-action@0.5.0
  #       with:
  #         access_token: ${{ github.token  }}
  #     - uses: actions/checkout@v2.3.3
  #     - name: Login to GitHub Container Registry
  #       uses: docker/login-action@v1
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.PAT }}
  #     - name: Build and push config container
  #       run: |
  #         docker build .github/docker --tag ghcr.io/evanriley/config:latest
  #         docker run ghcr.io/evanriley/config:latest
  #         docker push ghcr.io/evanriley/config:latest
